### ISSUE TITLE
Мьютекс, который не мьютекс

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_no_homomorphism#10]
https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/b181ef8d6c348cba2c1f344e4bb13c5f813912cf/handlers/user.go#L77-L78

Этот мьютекс не работает :) Мьютексы нужны, чтобы блокировать доступ к разделяемым ресурсам. Это значит, что у одного ресурса должен быть 1 мьютекс, логично? В вашем же случае мьютекс ни для кого не заблокирует доступ. Допустим у вас 1000 горутин. И каждая горутина создаст свой собственный мьютекс. В итоге все 1000 получат доступ к мэпе, не зная о существовании других мьютексов! 

Чтобы пофиксить это, создайте геттер у структуры UsersStorage. Там ведь как раз есть мьютекс, его и блокируйте. Только пусть геттер возвращает не `*User`, это опасно, ведь указатель может изменять оригинальный обьект. Пусть геттер возвращает `User`, тогда все будет безопасно

**Comment by bulletmys** [comment]
Это тоже было пофикшено далее

**Comment by SmartPhoneJava** [comment]
Это я не ту ветку смотрю(6-handlers-test) или оно еще не залито?

**Comment by bulletmys** [comment]
Ее смерджили с другой и теперь актуальная версия в predev

**Comment by SmartPhoneJava** [comment]
Понял, пойду ее гляну)
