### ISSUE TITLE
Int -> error -> int

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_no_homomorphism#11]
https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/handlers/user.go#L50-L66

Эти конвертации из int в error и обратно выглядит как минимум странно. Если функция с говорящим названием `Получить айди пользователя` вернула ошибку, то это всегда статус StatusUnauthorized. Не стоит шифровать статус возврата, возвращайте из функции реальные ошибки. И в случае, если эта функция вернула ошибку, сразу объявляйте StatusUnauthorized без колебаний)

**Comment by bulletmys** [comment]
Да, я сам сомневался над этим, уберу
