### ISSUE TITLE
Спрятанные ошибки

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_no_homomorphism#12]
Лучше не пропускать ошибки, замучаетесь разбираться, почему что то не работает)

https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/handlers/user.go#L69

https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/handlers/user.go#L141

https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/handlers/user.go#L148

https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/handlers/user.go#L154

**Comment by bulletmys** [comment]
Окей, пофиксим
