### ISSUE TITLE
Копирование файла

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_no_homomorphism#13]
https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/handlers/user.go#L154

А зачем копировать файл?

**Comment by bulletmys** [comment]
Это отправка файла на фронт

**Comment by SmartPhoneJava** [comment]
А, запись в ResponseWriter, понял)
