### ISSUE TITLE
дедлок при добавлении юзера

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_no_homomorphism#14]
Аккуратнее, при исправлении #7 появился другой баг - ретерн перед разблокировкой мьютекса

https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/models/user.go#L53-L57

**Comment by bulletmys** [comment]
Да, точно. Надо дефер перед if сделать
