### ISSUE TITLE
request body не требует закрытия

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_no_homomorphism#16]
https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/handlers/user.go#L163

https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/handlers/user.go#L185

https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/handlers/user.go#L210

https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/handlers/user.go#L257

https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/adf73f9382002dc83a06db0cf7afc2a6fdd2e809/handlers/user.go#L278

Если коротко, то в документации к http.Requst сказано
> For server requests, the Request Body is always non-nil but will return EOF immediately when no body is present. **The Server will close the request body. The ServeHTTP Handler does not need to**.

То есть если вы делаете запрос по http, то получив request body, надо его закрыть. Пример:
``` client := http.DefaultClient
resp, err := client.Do(req)
if err != nil {
    return nil, err
}
defer resp.Body.Close()
 ```
[Подробнее](https://stackoverflow.com/questions/42525499/where-to-put-defer-req-body-close)

**Comment by bulletmys** [comment]
```Golang
http.HandleFunc("/raw_body", func(w http.ResponseWriter, r *http.Request) {
		body, err := ioutil.ReadAll(r.Body)
		defer r.Body.Close() // важный пункт!
		if err != nil {
			http.Error(w, err.Error(), 500)
			return
		}
		fmt.Fprintf(w, "postHandler: raw body %s\n", string(body))
	})
```
Хм, просто про это говорили на лекции и я, когда смотрел в примерах, нашел закрытие боди запроса там. 
https://github.com/go-park-mail-ru/lectures/blob/master/3/2_http/40_requests.go#L22

**Comment by SmartPhoneJava** [comment]
Создал у них [ишью](https://github.com/go-park-mail-ru/lectures/issues/2), будем ждать комментариев)
