### ISSUE TITLE
Создание юзера из юзера

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_no_homomorphism#7]
https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/b181ef8d6c348cba2c1f344e4bb13c5f813912cf/models/user.go#L56-L60

А зачем создавать новый экземпляр `User`, если можно использовать тот, который пришел на вход, просто изменив его `Id`? 
И может стоит производить это действие до блокировки мьютекса?

**Comment by bulletmys** [comment]
Пофиксил
