### ISSUE TITLE
Мьютекс в UsersStorage

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_no_homomorphism#9]
В структуре UsersStorage у вас стоит мьютекс, который контролирует запись и чтению в мэпу `Users`, но что то пошло не так и мьютекс используется не везде...
https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/b181ef8d6c348cba2c1f344e4bb13c5f813912cf/models/user.go#L66-L76

https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/b181ef8d6c348cba2c1f344e4bb13c5f813912cf/models/user.go#L77-L79

https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/b181ef8d6c348cba2c1f344e4bb13c5f813912cf/models/user.go#L99

На секунду может показаться, что вы просто забыли его реализовать, но при добавлении юзера вы же им пользуйтесь :)
https://github.com/go-park-mail-ru/2020_1_no_homomorphism/blob/b181ef8d6c348cba2c1f344e4bb13c5f813912cf/models/user.go#L55-L62

Добавьте же его и в другие места обращения к мэпе. И переходите на  [sync.RWMutex](https://golang.org/pkg/sync/#RWMutex). У него отдельный механизм для блокировки на запись/чтение.

P.S. Поля, защищенные мьютексом, не должны быть импортируемыми. Представьте, что вам через пол года пришлось дописывать проект. Вы точно забудете, что поставили мьютекс для мэпы. Облегчите себе жизнь - пометьте, что данное поле **явно** защищено мьютексом. Переименуйте `Users` в `_users`.

P. P. S. Определяя структуру, в которой мьютекс должен защищать одно или больше значений, помещайте мьютекс выше тех полей, доступ к которым, он будет защищать. [Подробнее](https://habr.com/ru/post/271789/)

**Comment by bulletmys** [comment]
Мьютексы были добавлены в  те места функций моделей в последующих коммитах. Спасибо за ревью, изучим подробнее мьютекс
